
development:
  adapter: postgresql
  database: js_ru_development
  pool: 5
  timeout: 5000
  username: postgres
  password:

test:
  adapter: postgresql
  database: js_ru_test
  pool: 5
  timeout: 5000
  username: postgres
  password:

production:
  adapter: postgresql
  database: js_ru_production
  pool: 5
  timeout: 5000
  username: postgres
  password:
